modLoader = "javafml"
loaderVersion = "[47,)" # Forge 1.20.1 uses 47.x
license = "MIT"

[[mods]]
modId = "furnituresoplenty"
version = "${mod_version}"
displayName = "Furnitures O' Plenty"
authors = "RSlover521"
description = '''
A beautiful furniture mod combining Refurbished Furniture and Biomes O' Plenty aesthetics.
'''
credits="RSlover521"
logoFile="furnituresoplenty_icon.png"
bannerFile="furnituresoplenty_banner.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/furnitures-o-plenty"
issueTrackerURL="https://github.com/RSlover521/Furnitures-O-Plenty/issues"

# Dependencies
[[dependencies.furnituresoplenty]]
    modId = "refurbished_furniture"
    mandatory = true
    versionRange = "[1.0.14,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.furnituresoplenty]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[19.0.0.90,)"
    ordering="AFTER"
    side="BOTH"